config/routes.rb
PropertyManager::Application.routes.draw do
  root to: 'buildings#index'

  resources :buildings, only: [:index, :new, :create]
  resources :owners, only: [:index, :new, :create, :destroy]
end

app/models/building.rb
class Building < ActiveRecord::Base
  STATES =  %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)

  validates_presence_of :street_address
  validates_presence_of :city
  validates :state, presence: :true, inclusion: { in: STATES }
  validates :zip_code, presence: :true, format: { with: /\A\d{5}\z/}

  belongs_to :owner

  def owner_name
    if owner.nil?
      ""
    else
      owner.name
    end
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }

  has_many :buildings, dependent: :nullify

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
    @buildings = Building.all
  end

  def new
    @building = Building.new
    @owners = Owner.all
  end

  def create
    @building = Building.new(building_params)
    if @building.save
      redirect_to new_building_path, notice: 'Successfully recorded building!'
    else
      flash[:notice] = 'Uh oh!  We ran into some errors.'
      render 'new'
    end
  end

  private

  def building_params
    params.require(:building).permit(:street_address, :city, :state, :zip_code, :description, :owner_id)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to new_owner_path, notice: 'Successfully recorded owner!'
    else
      flash[:notice] = 'Uh oh!  We encountered a problem.'
      render 'new'
    end
  end

  def destroy
    @owner = Owner.find(params[:id])
    if @owner.destroy
      redirect_to owners_path, notice: 'Owner deleted.'
    else
      flash[:notice] = 'Uh oh!  We encountered a problem.'
      render 'index'
    end
  end

  private

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/index.html.erb
<h2>All Buildings</h2>

<table>
  <tr>
    <th>Address</th>
    <th>Owner</th>
  </tr>
<% @buildings.each do |building| %>
<tr>
  <td><%= "#{building.street_address}, #{building.city}, #{building.state}" %></td>
  <td><%= building.owner_name %></td>
<% end %>
</table>

<br>
<ul class="links">
  <li><%= link_to 'Add Building', new_building_path %></li>
  <li><%= link_to 'Add Owner', new_owner_path %></li>
  <li><%= link_to 'View Owners', owners_path %></li>
</ul>

app/views/buildings/new.html.erb
<h2>Add New Building</h2>

<%= simple_form_for @building do |f| %>
  <%= f.input :street_address, label: 'Street Address' %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zip_code, label: 'Zip Code' %>
  <%= f.input :description %>
  <%= f.association :owner, collection: @owners %>
  <%= f.submit 'Create Building' %>
<% end %>

<br>
<%= link_to 'Back', buildings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PropertyManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/owners/index.html.erb
<h2>All Owners</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Company</th>
  </tr>
<% @owners.each do |owner| %>
<tr>
  <td><%= owner.name %></td>
  <td><%= owner.email %></td>
  <td><%= owner.company %></td>
  <td><%= link_to 'Delete', owner_path(owner), method: :delete %></td>
<% end %>
</table>

<br>
<%= link_to 'Back', buildings_path %>

app/views/owners/new.html.erb
<h2>Add New Owner</h2>

<%= simple_form_for @owner do |f| %>
  <%= f.input :first_name, label: 'First Name' %>
  <%= f.input :last_name, label: 'Last Name' %>
  <%= f.input :email %>
  <%= f.input :company %>
  <%= f.submit 'Create Owner' %>
<% end %>

<br>
<%= link_to 'Back', buildings_path %>